const pokemons = [
  {
    abilities: ["Overgrow"],
    number: "001",
    weight: 6.9,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    height: 0.7,
    featured: "true",
    slug: "bulbasaur",
    name: "Bulbasaur",
    id: 1,
    type: ["grass", "poison"],
    ThumbnailAltText: "Bulbasaur",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  },
  {
    abilities: ["Overgrow"],
    number: "002",
    weight: 13,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    height: 1,
    featured: "true",
    slug: "ivysaur",
    name: "Ivysaur",
    id: 2,
    type: ["grass", "poison"],
    ThumbnailAltText: "Ivysaur",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png",
  },
  {
    abilities: ["Overgrow"],
    number: "003",
    weight: 9999,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    height: 24,
    featured: "true",
    slug: "venusaur",
    name: "Venusaur",
    id: 3,
    type: ["grass", "poison"],
    ThumbnailAltText: "Venusaur",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png",
  },
  {
    abilities: ["Keen Eye", "Sand Rush"],
    number: "745",
    weight: 25,
    weakness: ["Water", "Steel", "Grass", "Fighting", "Ground"],
    height: 0.8,
    featured: "true",
    slug: "lycanroc",
    name: "Lycanroc",
    id: 745,
    type: ["rock"],
    ThumbnailAltText: "Lycanroc",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/745.png",
  },
  {
    abilities: ["Schooling"],
    number: "746",
    weight: 78.6,
    weakness: ["Grass", "Electric"],
    height: 8.2,
    featured: "true",
    slug: "wishiwashi",
    name: "Wishiwashi",
    id: 746,
    type: ["water"],
    ThumbnailAltText: "Wishiwashi",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/746.png",
  },
  {
    abilities: ["Blaze"],
    number: "004",
    weight: 8.5,
    weakness: ["Water", "Ground", "Rock"],
    height: 0.6,
    featured: "true",
    slug: "charmander",
    name: "Charmander",
    id: 4,
    type: ["fire"],
    ThumbnailAltText: "Charmander",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
  },
  {
    abilities: ["Blaze"],
    number: "005",
    weight: 19,
    weakness: ["Water", "Ground", "Rock"],
    height: 1.1,
    featured: "true",
    slug: "charmeleon",
    name: "Charmeleon",
    id: 5,
    type: ["fire"],
    ThumbnailAltText: "Charmeleon",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png",
  },
  {
    abilities: ["Blaze"],
    number: "006",
    weight: 9999,
    weakness: ["Water", "Electric", "Rock"],
    height: 28,
    featured: "true",
    slug: "charizard",
    name: "Charizard",
    id: 6,
    type: ["fire", "flying"],
    ThumbnailAltText: "Charizard",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png",
  },
  {
    abilities: ["Limber", "Merciless"],
    number: "747",
    weight: 8,
    weakness: ["Psychic", "Electric", "Ground"],
    height: 0.4,
    featured: "true",
    slug: "mareanie",
    name: "Mareanie",
    id: 747,
    type: ["poison", "water"],
    ThumbnailAltText: "Mareanie",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/747.png",
  },
  {
    abilities: ["Own Tempo", "Stamina"],
    number: "749",
    weight: 110,
    weakness: ["Water", "Grass", "Ice"],
    height: 1,
    featured: "true",
    slug: "mudbray",
    name: "Mudbray",
    id: 749,
    type: ["ground"],
    ThumbnailAltText: "Mudbray",
    ThumbnailImage: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/749.png",
  },
];

export const getPokemons = () => {
  return new Promise((resolve) => {
    setTimeout(resolve, 1000, pokemons);
  });
};
